# Generated by Django 4.1 on 2022-08-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caitandnatewedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='rsvp_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
