# Generated by Django 4.1 on 2022-08-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caitandnatewedding', '0002_household_rsvp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='guest',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Miss', 'Miss'), ('Dr.', 'Dr.'), ('Reverend Father', 'Reverend Father')], max_length=55),
        ),
    ]
