# Generated by Django 4.1 on 2022-08-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caitandnatewedding', '0003_alter_guest_first_name_alter_guest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
