# Generated by Django 4.1 on 2022-08-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caitandnatewedding', '0004_alter_guest_middle_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='rsvp_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
