# Generated by Django 4.1 on 2022-08-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caitandnatewedding', '0005_alter_household_rsvp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Miss', 'Miss'), ('Dr.', 'Dr.'), ('Reverend Father', 'Reverend Father'), ('Sister', 'Sister')], max_length=55),
        ),
    ]
